- block:
  - name: create additional volumes
    os_volume:
      auth:  "{{ vars['os_auth_hailstorm_' + osp_tenant.replace('-','_')] }}"
      size: "{{ (item.0/1024/1024/1024)|int|abs }}"
      display_name:  "{{ inventory_hostname_short }}-{{ item.1 }}"
      validate_certs: False
    when: (item.0 != None) and (item.1 != None)
    with_together:
      - "{{ vm_additional_disks|default([]) }}"
      - ['vdb','vdc','vdd']

  - name: attach additional volumes
    os_server_volume:
      auth:  "{{ vars['os_auth_hailstorm_' + osp_tenant.replace('-','_')] }}"
      server: "{{ inventory_hostname_short }}"
      volume: "{{ inventory_hostname_short }}-{{ item.1 }}"
      validate_certs: False
      device: "/dev/{{ item.1 }}"
    when: (item.0 != None) and (item.1 != None)
    with_together:
      - "{{ vm_additional_disks|default([]) }}"
      - ['vdb','vdc','vdd']

  delegate_to: localhost
