- block:
    - name: create userdata file
      template: "src=cloud-config.txt.j2 dest=/tmp/{{ osp_tenant }}_{{ inventory_hostname_short }}_userdata.txt"

    - name: instantiate image
      delegate_to: localhost
      os_server:
        auth: "{{ vars['os_auth_hailstorm_' + osp_tenant.replace('-','_')] }}"
        name: "{{ inventory_hostname_short }}"
        userdata:  "{{ lookup('file','/tmp/{{ osp_tenant }}_{{ inventory_hostname_short }}_userdata.txt') }}"
        image:  "{{ osp_image }}"
        flavor: "{{ osp_flavor }}"
        nics: >
          [ {% for network in vm_nics %}
                {'net-name': '{{ network.netname|regex_replace('rhosp_','') }}' }
            {% if not loop.last %},{% endif %}
            {% endfor %} ]
        auto_ip: False
        security_groups: "{% if vm_secgroups is defined and vm_secgroups %}{{  secgroup in vm_secgroups|default([])|join(',') }}{% else %}default-{{osp_tenant}}{% endif %}"
        availability_zone: "nova"
        validate_certs: False

  delegate_to: localhost
