- name: terminate instance
  delegate_to: localhost
  os_server:
    state: absent
    auth: "{{ vars['os_auth_hailstorm_' + osp_tenant.replace('-','_')] }}"
    name: "{{ inventory_hostname_short }}"
    validate_certs: False
