- name: check for existence of config (via created hosts file)
  stat: path="~{{ nuage_user }}/nuage-metro/hosts"
  register: has_nuconfiguration

- debug:
    msg: "ATTENTION: WE WILL NOT ROLLOUT ANYTHING HERE FOR NUAGE!!! There is already a nuage configuration, so we assume that the appliances are already rolled out."
    verbosity: 0
  when: has_nuconfiguration.stat.exists == True

- block:
    - name: Phase I) initial build - base variables and hosts
      shell: source ansible-2.2.1.0/bin/activate && cd nuage-metro && ansible-playbook -vv -i hosts_sddc -e "build_vars_file=ha_build_vars.yml" build.yml -t always

    - name: add hosts to hosts_sddc
      shell: cd nuage-metro && cat hosts >> hosts_sddc

    - name: Phase II) sw unpack - phase I was needed for that
      shell: source ansible-2.2.1.0/bin/activate && cd nuage-metro && ansible-playbook -vv -i hosts_sddc -e "build_vars_file=ha_build_vars.yml" nuage_unzip.yml

    - name: Phase III) build configs - configs for all products are created here
      shell: source ansible-2.2.1.0/bin/activate && cd nuage-metro && ansible-playbook -vv -i hosts_sddc -e "build_vars_file=ha_build_vars.yml" build.yml

    - name: Phase IV) install
      shell: source ansible-2.2.1.0/bin/activate && cd nuage-metro && ansible-playbook -vv -i hosts_sddc -e "build_vars_file=ha_build_vars.yml" install_vcs.yml
  when: has_nuconfiguration.stat.exists == False
  become: yes
  become_user: "{{ nuage_user }}"
