- block:
    - name: Phase I) initial build - base variables and hosts
      shell: source ansible-2.2.1.0/bin/activate && cd nuage-metro && ansible-playbook -vv -i hosts_sddc -e "build_vars_file=ha_build_vars.yml" build.yml -t always

    - name: add hosts to hosts_sddc
      shell: cd nuage-metro && cat hosts >> hosts_sddc

    - name: Phase II) sw unpack - phase I was needed for that
      shell: source ansible-2.2.1.0/bin/activate && cd nuage-metro && ansible-playbook -vv -i hosts_sddc -e "build_vars_file=ha_build_vars.yml" nuage_unzip.yml

    - name: Phase III) build configs - configs for all products are created here
      shell: source ansible-2.2.1.0/bin/activate && cd nuage-metro && ansible-playbook -vv -i hosts_sddc -e "build_vars_file=ha_build_vars.yml" build.yml

    - name: Phase IV) install
      shell: source ansible-2.2.1.0/bin/activate && cd nuage-metro && ansible-playbook -vv -i hosts_sddc -e "build_vars_file=ha_build_vars.yml" install_vcs.yml
  become: yes
  become_user: "{{ nuage_user }}"
