- name: create nuage user
  user:
    name: "{{ nuage.user }}"
    state: present
    comment: Nuage installation user
    generate_ssh_key: yes

- name: Get authorized key just generated for nuage user as variable
  shell: cat ~{{ nuage.user }}/.ssh/id_rsa.pub
  register: nuage_ssh_pubkey

- name: Set authorized key for root
  authorized_key:
    user: root
    state: present
    key: "{{ nuage_ssh_pubkey.stdout }}"

- name: remove known_hosts
  file:
    path: "~{{ nuage.user }}/.ssh/know_hosts"
    state: absent

- name: make sudoers file for nuage user
  shell: echo "{{ nuage.user }} ALL=(root) NOPASSWD:ALL" | tee /etc/sudoers.d/{{ nuage.user }}

- name: set default password
  shell: echo {{ root_password }} | passwd --stdin {{ nuage.user }}

- include: make_nuage_directories.yml directory={{ item }}
  with_items:
    - share
    - "{{ nuage.metro_bins }}"
    - binaries-unpacked

- name: make fstab entry to allow to mount binaries from layer1 host (mainly to copy back changes or backups for convenience)
  mount:
    path: "~{{ nuage.user }}/share"
    src: "{{ infrastructure_network_storage.default_gw_host_prefix | ipaddr('address') }}:{{ nfs_nuage_binary_dir }}"
    fstype: nfs
    opts: ro,noauto
    state: present

#- name: check for {{ nuage.metro_bins }} directory
#  stat: path="~{{ nuage.user }}/{{ nuage.metro_bins }}"
#  register: has_nubin_dir

#- name: create {{ nuage.metro_bins }} directory
#  file:
#    path: "~{{ nuage.user }}/{{ nuage.metro_bins }}"
#    state: directory
#    mode: 0700
#    owner: "{{ nuage.user }}"
#    group: "{{ nuage.user }}"
#  when: has_nubin_dir.stat.exists == False

- name: copy over needed hailstorm parts
  synchronize:
    src: "{{ item }}"
    dest: "~{{ nuage.user }}/{{ nuage.metro_bins }}"
    use_ssh_args: yes
  with_items:
    - binary/{{ hailstorm_ssh_priv_key_file }}
    - binary/{{ hailstorm_ssh_priv_key_file }}.pub
    - ansible_ssh_config

- name: make binary link
  file:
    state: link
    src: "~{{ nuage.user }}/"
    dest: "~{{ nuage.user }}/binary"

# there are 2 ways to get the binaries:
# (1) copy over from the ansible/binary/{{ nuage.metro_bins }} directory of the user running this playbook
- name: install nuage-metro bins
  synchronize:
    src: "../../../binary/{{ nuage.metro_bins }}"
    dest: "~{{ nuage.user }}"
    use_ssh_args: yes
- name: move the bins to ~
  shell: rsync -aviPHAXS ~{{ nuage.user }}/{{ nuage.metro_bins }}/* ~{{ nuage.user }}/ && rm -Rf ~{{ nuage.user }}/{{ nuage.metro_bins }}
- name: correct ownership
  file:
    path: "~{{ nuage.user }}"
    owner: "{{ nuage.user }}"
    group: "{{ nuage.user }}"
    recurse: yes
# (2) copy over everything that is missing from the {{ layer1_ansible_host }}
- include: copy_nuage_bins.yml file={{item}}
  with_items:
    - binaries
    - licenses
    - "{{ nuage.metro_bins }}"
- name: move the bins to ~
  shell: rsync -aviPHAXS ~{{ nuage.user }}/{{ nuage.metro_bins }}/* ~{{ nuage.user }}/ && rm -Rf ~{{ nuage.user }}/{{ nuage.metro_bins }}
- name: correct ownership again
  file:
    path: "~{{ nuage.user }}"
    owner: "{{ nuage.user }}"
    group: "{{ nuage.user }}"
    recurse: yes

- block:
    - name: unpack nuage-metro installer
      unarchive:
        remote_src: yes
        src: "nuage-metro-latest.tar.gz"
        dest: "~"

    - name: mv some files to the nuage-metro installer directory
      shell: mv "{{ item }}" nuage-metro
      with_items:
        - binary
        - ansible_ssh_config

    - name: mv the rpms to the binaries-unpacked directory
      shell: mv *.rpm binaries-unpacked

    - name: Install pip modules
      pip:
        name: "{{item}}"
        state: present
        virtualenv: "~/ansible-2.2.1.0"
        virtualenv_python: python2.7
      with_items:
        - enum
        - netaddr
        - ipaddr
        - pexpect
        - vspk
        - pyvmomi 

    - name: Upgrade pip modules
      pip:
        name: "{{item}}"
        state: latest
        virtualenv: "~/ansible-2.2.1.0"
      with_items:
        - pip
        - virtualenv
        - virtualenvwrapper
        - pytz
        - setuptools

    - name: Install shade
      pip:
        name: "{{item}}"
        state: present
        virtualenv: "~/ansible-2.2.1.0"
      with_items:
        - ansible==2.2.1.0
        - shade
        - netmiko

    - name: create nuage config
      vars:
        vsd_fqdn_global: "xmpp.{{ hailstorm_dns_domain }}"
      template:
        src: templates/ha_build_vars.yml.j2
        dest: nuage-metro/ha_build_vars.yml
        mode: 0644

    - name: create hosts_sddc for nuage
      template:
        src: ../../../hosts_sddc
        dest: nuage-metro/hosts_sddc
        mode: 0644

    - name: delete broken VIP in hosts_sddc (Attention! VIP in hosts_sddc seems to be broken anyway)
      lineinfile:
        path: nuage-metro/hosts_sddc
        state: absent
        regexp: '^undercloud-public ansible_host='
  become: yes
  become_user: "{{ nuage.user }}"
