- name: create ansible inventory as /etc/ansible/hosts
  shell: . ~/stackrc && tripleo-ansible-inventory --static-inventory ansible_hosts && sudo cp ansible_hosts /etc/ansible/hosts
  become: yes
  become_user: "{{ rhosp_stack_user }}"
  changed_when: false
