- name: Get list of the nodes
  shell: . ~/stackrc && openstack server list -f value -c Name
  become: yes
  register: rhosp_nodes
  become_user: "{{ rhosp_stack_user }}"

- name: Unregister nodes from satellite
  shell: hammer host delete --name "{{ item }}" || hammer host delete --name "{{ item }}.{{ node_hailstorm_dns_domain }}"
  with_items: "{{ rhosp_nodes.stdout_lines }}"
  delegate_to: satellite
  ignore_errors: True # Maybe the node was not correctly registered, so better ignore errors and continue

- name: delete overcloud heat stack
  shell: . ~/stackrc && heat stack-list | grep overcloud && heat stack-delete {{ stack_name }} -y || true
  ignore_errors: true
  become: yes
  become_user: "{{ rhosp_stack_user }}"
  register: stack
  until: stack.stdout == ""
  failed_when: "'FAILED' in stack.stdout"
  retries: 30
  delay: 60
