- name: read CMS ID into variable
  slurp:
    src: /home/{{ rhosp_stack_user }}/nuage-ospdirector-ML2-SRIOV/generate-cms-id/cms_id.txt
  register: nuage_cms_id
  when: nuage is defined
- debug: var=nuage_cms_id
  when: nuage is defined
# use with: nuage_cms_id['content'] | b64decode

- block:
    - include: prepare_director.yml
      tags: ['prep-director']
    - include: register_overcloud_nodes.yml
      tags: ['register']
    - include: create_overcloud.yml
      tags: ['overcloud-deploy']
      vars:
        templates:
          - commandlineparams-environment.yaml
          - network-isolation.yaml
          - network-environment.yaml
          - ips-from-pool-environment.yaml
          - extra-config-post-deployment-environment.yaml
          - extra-config-post-deployment.yaml
          - extra-config-post-deployment-all.sh
          - ceilometer-config-environment.yaml
          - "{% if current_lifecycle_env.osp_storage_backend == 'ceph_ownvms' %}storage-ceph-environment.yaml{% elif current_lifecycle_env.osp_storage_backend == 'ceph_hyperconverged' %}storage-ceph-hyperconverged-environment.yaml{% elif current_lifecycle_env.osp_storage_backend == 'nfs_layer1' %}storage-nfs-environment.yaml{% endif %}"
          - firstboot-config-environment.yaml
          - firstboot-config.yaml
          - firstboot-config-rootsshkey.sh
          - firstboot-config-setrootpw.sh
          - firstboot-config-prep-ceph-disks.sh
          - rhel-registration-environment.yaml
          #- rhel-registration.yaml
          #- rhel-registration.sh
          - timezone-environment.yaml
          - hostname-map-environment.yaml
          - schedulerhints-environment.yaml
          - dns-config-environment.yaml
          - tls-enable-environment.yaml
          - tls-inject-trust-anchor-environment.yaml
          - monitoring-environment.yaml
          - logging-environment.yaml
          - "{% if nuage is defined %}neutron-nuage-config.yaml{% endif %}"
          - "{% if nuage is defined %}nova-nuage-config.yaml{% endif %}"
  when: mode=="create"

- block:
    - include: destroy_overcloud.yml
      tags: ['overcloud-deploy']
    - include: unregister_overcloud_nodes.yml
      tags: ['register']
  when: mode=="destroy"

- block:
    - include: scale_down_via_hostname.yml
      static: no
      vars:
        templates:
          - commandlineparams-environment.yaml
          - network-isolation.yaml
          - network-environment.yaml
          - ips-from-pool-environment.yaml
          - extra-config-post-deployment-environment.yaml
          - extra-config-post-deployment.yaml
          - extra-config-post-deployment-all.sh
          - ceilometer-config-environment.yaml
          - "{% if current_lifecycle_env.osp_storage_backend == 'ceph_ownvms' %}storage-ceph-environment.yaml{% elif current_lifecycle_env.osp_storage_backend == 'ceph_hyperconverged' %}storage-ceph-hyperconverged-environment.yaml{% elif current_lifecycle_env.osp_storage_backend == 'nfs_layer1' %}storage-nfs-environment.yaml{% endif %}"
          - firstboot-config-environment.yaml
          - firstboot-config.yaml
          - firstboot-config-rootsshkey.sh
          - firstboot-config-setrootpw.sh
          - firstboot-config-prep-ceph-disks.sh
          - rhel-registration-environment.yaml
          #- rhel-registration.yaml
          #- rhel-registration.sh
          - timezone-environment.yaml
          - hostname-map-environment.yaml
          - schedulerhints-environment.yaml
          - dns-config-environment.yaml
          - tls-enable-environment.yaml
          - tls-inject-trust-anchor-environment.yaml
          - monitoring-environment.yaml
          - logging-environment.yaml
          - "{% if nuage is defined %}neutron-nuage-config.yaml{% endif %}"
          - "{% if nuage is defined %}nova-nuage-config.yaml{% endif %}"
  when: mode=="reset"
