- stat: path=/home/stack/bin/osp-status.sh
  register: already_prepared
#- debug: var=already_prepared

- block:
  - name: Create bin directory
    file: path=~/bin state=directory
  - name: install helper binaries for operation of RHOSP
    copy: src="{{ item }}" dest=/home/stack/bin/ owner=stack mode=755
    with_fileglob:
      - files/*
  - name: install more helper files for operation of RHOSP
    copy: src="{{ item }}" dest=/home/stack/ owner=stack mode=644
    with_fileglob:
      - files/.screenrc
  - name: symlink some directories for convenience
    file: src=/usr/share/openstack-tripleo-heat-templates/network dest=/home/stack/network state=link
  - name: symlink some directories for convenience
    file: src=/usr/share/openstack-tripleo-heat-templates/puppet dest=/home/stack/puppet state=link
  - name: extend .bashrc_profile to use stackrc by default and inhibit ssh to save HostKeys
    lineinfile:
      path: /home/stack/.bash_profile
      line: 'source ~/stackrc'
  - lineinfile:
      path: /home/stack/.bash_profile
      line: 'PSSH="-oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q"'
  - lineinfile:
      path: /home/stack/.bash_profile
      line: 'alias ssh="ssh $PSSH"'
  when: already_prepared.stat.exists == False
