- name: configure appliance
  shell: /var/www/miq/vmdb/bin/rails runner 'MiqServer.my_server.set_config({{ item.key }} => {{ item.value }})'
  with_dict: "{{cfme_settings2}}"

#  /var/www/miq/vmdb/bin/rails runner 'MiqServer.my_server.set_config(:authentication => {:mode=>"httpd", :local_login_disabled=>false, :saml_enabled=>true, :sso_enabled=>false, :user_proxies=>[{}], :httpd_role=>true, :amazon_role=>false, :ldap_role=>false})'
# bin/rails r "puts Zone.find_by(:name => 'OSP')[:id]"

- name: make sure evmserverd is restarted
  service: name=evmserverd state=restarted enabled=yes

- name: wait for cfme web ui to become available again
  wait_for: host="{{ ansible_host }}" port=443 timeout=600
  delegate_to: "{{ jump_host|default(infrastructure_delegate_host_used_to_test_if_layer2_host_is_available) }}"

- name: create export script
  template: src=export.sh.j2 dest=~/export.sh owner=root group=root mode=0755
