---
mem: 12288
vcpu: 4
disk:
  size: 50

vm_secgroups:
  - webserver-{{ cf_tenant }}
  - default-{{ cf_tenant }}

nic_attachments:
  - "{{ infrastructure_osp_tenant_internal_network }}"
#  - "{{ infrastructure_network_services }}"
#  - "{{ infrastructure_network_admin }}"
#  - "{{ infrastructure_network_storage }}"
#  - "{{ infrastructure_network_provisioning }}"
# default_route_via: "{{ infrastructure_network_services }}"
# name_service_via: "{{ infrastructure_network_services }}"
