---
vm_additional_disks:
  - 26843545600
  - 107374182400

nic_attachments:
  - "{{ infrastructure_network_services }}"
  - "{{ infrastructure_network_admin }}"
  - "{{ infrastructure_network_rhosp_provisioning }}"
default_route_via: "{{ infrastructure_network_services }}"
name_service_via: "{{ infrastructure_network_services }}"

vm_secgroups:
    - webserver
    - default

repos: "{{ cloudforms_repos }}"
pool_regex: "{{ cloudforms_subscription_pool_regex }}"
packages_uninstall: cloud-init
ntp_client: will_be_configured_in_the_cf_config_role

tdagent_configs:
  - tag: evm.log
    path: /var/www/miq/vmdb/log/evm.log
    pos_file: /var/log/td-agent/evm_log.pos
    format: multiline
    format_firstline: '/^\[----\].*/'
    format1: '/^\[----\]\ [A-Z],\ \[(?<time>[^\ ]*)\ #(?<pid>[0-9]*):(?<thread>[\h]*)\]\s+(?<loglevel>[A-Z]*)\ --\ :(?<message>.*)/'
    time_format: "%Y-%m-%dT%H:%M:%S.%N"
    permissions:
      - path: /var/www/miq/vmdb/log/evm.log
        mode: o+xr
