---
mem: 4096
vcpu: 2
disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 40
  format: qcow2
  # partition_table:
  #   lvmpv: 29500
  #   swap: 2048
  #   home: 2048
  #   root: 10000
  physvols:
    boot: 500
    rhel: 39500
  logvols:
    - name: swap
      fstype: swap
      mountpoint: swap
      size: 2048
    - name: root
      fstype: "{{ fstype }}"
      mountpoint: /
      size: 10000
    - name: home
      fstype: "{{ fstype }}"
      mountpoint: /home
      size: 2048
    - name: varlog
      fstype: "{{ fstype }}"
      mountpoint: /var/log
      size: 20000

repos:
  - rhel-7-server-rpms
packages: bind,dovecot,postfix
pool_regex: "{{ rhel_subscription_pool_regex }}"

catch_all_user: catchall

firewalld_rules:
 - DNStcp:
   port: 53
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - DNSudp:
   port: 53
   protocol: udp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - SMTP:
   port: 25
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - IMAP:
   port: 143
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - IMAPSSL:
   port: 993
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - NTPudp:
   port: 123
   protocol: udp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - ELAtcp:
   port: 9200
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - SYSLOGtcp:
   port: 514
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - SYSLOGudp:
   port: 514
   protocol: udp 
   state: enabled
   zone: public
   permanent: true
   immediate: true





tdagent_configs:
 - tag: syslog.messages
   path: /var/log/messages
   pos_file: /var/log/td-agent/messages_log.pos
   format: syslog
   permissions:
    - path: /var/log/messages
      mode: o+r
