---
mem: 1024
vcpu: 2

disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 100
  format: qcow2
  # partition_table:
  #   lvmpv: 29500
  #   swap: 2048
  #   home: 2048
  #   root: 10000

  physvols:
    boot: 500
    rhel: 99500
  logvols:
    - name: swap
      fstype: swap
      mountpoint: swap
      size: 2048
    - name: root
      fstype: "{{ fstype }}"
      mountpoint: /
      size: 10000
    - name: home
      fstype: "{{ fstype }}"
      mountpoint: /home
      size: 70000

pool_regex: "{{ rhel_subscription_pool_regex }}"
repos:
  - rhel-7-server-rpms
  - rhel-7-server-optional-rpms
  - rhel-7-server-extras-rpms

packages:
  - git
  - python
  - mc
  - strace
  - nmap
  - screen
  - iotop
  - gcc
  - python-devel
  - tmux
  - rsync
  - vim

# Nuage related stuff
nuage_user: "nuage"
# directory under ansible/binary, where the nuage binaries are stored
nuage_metro_bins: "nuage"
# bridges for the external network on the KVM host
ports_to_hv_bridges_vsr1: "['tenant','services','ospf1','bgp1','nuage_vsr'{% if infrastructure_network_guests.physical_underlay == false %},'guests'{% endif %}]"
ports_to_hv_bridges_vsr2: "['tenant','services','ospf2','bgp2','nuage_vsr'{% if infrastructure_network_guests.physical_underlay == false %},'guests'{% endif %}]"
