---
mem: 2048
vcpu: 2
disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 30
  format: qcow2
  # partition_table:
  #   lvmpv: 29500
  #   swap: 2048
  #   home: 2048
  #   root: 10000
  physvols:
    boot: 500
    rhel: 29500
  logvols:
    - name: swap
      fstype: swap
      mountpoint: swap
      size: 2048
    - name: root
      fstype: "{{ fstype }}"
      mountpoint: /
      size: 10000
    - name: home
      fstype: "{{ fstype }}"
      mountpoint: /home
      size: 2048

nic_attachments:
  - "{{ infrastructure_network_services }}"
  - "{{ infrastructure_network_admin }}"
  - "{{ infrastructure_network_guests|combine({'dhcp': true}) }}"
default_route_via: "{{ infrastructure_network_guests }}"
name_service_via: "{{ infrastructure_network_guests }}"

pool_regex: "{{ rhel_subscription_pool_regex }}"
repos:
  - rhel-7-server-rpms

packages: squid
# disable_services:
#   - NetworkManager


# firewalld_rules:
#   - Squid:
#     port: 8443
#     protocol: tcp
#     state: enabled
#     zone: public
#     permanent: true
#     immediate: true
