---
mem: 2048
vcpu: 2
disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 30
  format: qcow2
  # partition_table:
  #   lvmpv: 29500
  #   swap: 2048
  #   home: 2048
  #   root: 10000
  physvols:
    boot: 500
    rhel: 29500
  logvols:
    - name: swap
      fstype: swap
      mountpoint: swap
      size: 2048
    - name: root
      fstype: "{{ fstype }}"
      mountpoint: /
      size: 10000
    - name: home
      fstype: "{{ fstype }}"
      mountpoint: /home
      size: 2048

repos:
  - rhel-7-server-rpms
packages: rsyslog
pool_regex: "{{ rhel_subscription_pool_regex }}"

catch_all_user: catchall

firewalld_rules:
 - SYSLOGtcp:
   port: 514
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - SYSLOGudp:
   port: 514
   protocol: udp
   state: enabled
   zone: public
   permanent: true
   immediate: true

tdagent_configs:
 - tag: syslog.messages
   path: /var/log/messages
   pos_file: /var/log/td-agent/messages_log.pos
   format: syslog
   permissions:
    - path: /var/log/messages
      mode: o+r
