### IPA
- block:
    - shell: echo {{ hostvars['ipa'].ipa_admin_password }} | kinit admin && ipa dnsrecord-del {{ hailstorm_dns_domain }} {{ item }} --a-rec={{ ip }}
      register: iparecord
      failed_when: iparecord.rc != 0 and 'DNS resource record not found' not in iparecord.stderr and 'A record does not contain' not in iparecord.stderr
  delegate_to: ipa

### DNAT DNS
- block:
    - name: add or change host in zone db
      lineinfile:
        dest: "/etc/named/zones/master/db.{{ hailstorm_dns_domain }}"
        regexp: "^{{ item|regex_escape }}\\s+.*"
        state: absent
      notify:
        - create serial
        - update serial
        - restart named
  when: not skip_dnat_dns|default(false,true)
  delegate_to: infrastructure


### AD DNS
# work around the problem that delegating to AD does not seem to pull the proper variables from the AD host
- set_fact:
    ansible_winrm_server_cert_validation: ignore
- name: test if AD is available for remote management
  shell: curl -k https://{{ hostvars[groups['primary-ad-group'][0]].ansible_host }}:5986
  register: ad_available
  changed_when: false
  delegate_to: "{{ infrastructure_delegate_host_used_to_test_if_layer2_host_is_available }}"
  failed_when: false

- block:
    - name: remove existing A record
      win_shell: Remove-DnsServerResourceRecord -ZoneName {{ hailstorm_dns_domain }} -Name {{ item }} -RRType A -Force
      failed_when: false

  when: ad_available.stdout != ''
  delegate_to: "{{groups['primary-ad-group'][0]}}"
