### LAYER1 HOST
- block:
    - name: add or change {{ item }} in layer1 /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: "{{ ip }} {% for n in names %}{% if n != '' and n[0] != '*' %} {{ n }} {{ n }}.{{ hailstorm_dns_domain }}{% endif %}{% endfor %}.*$"
        state: absent
  delegate_to: layer1
