

- block:
    - include: configure_security_group.yml
      when: outer_item.security_groups is defined
      with_items: "{{ osp_projects }}"
      loop_control:
         loop_var: outer_item

    - name: create security group default-project for each project
      os_security_group:
        auth: "{{ vars['os_auth_hailstorm_' + item.name.replace('-','_')] }}"
        name: "default-{{ item.name }}"
        validate_certs: False
      with_items: "{{ osp_projects }}"

    - name: configure basic rule for new default-project sg
      os_security_group_rule:
        auth: "{{ vars['os_auth_hailstorm_' + item.name.replace('-','_')] }}"
        security_group: "default-{{ item.name }}"
        remote_group: "default-{{ item.name }}"
        validate_certs: False
      with_items: "{{ osp_projects }}"

    - name: configure basic rule for new default-project sg (IPv6)
      os_security_group_rule:
        auth: "{{ vars['os_auth_hailstorm_' + item.name.replace('-','_')] }}"
        security_group: "default-{{ item.name }}"
        remote_group: "default-{{ item.name }}"
        ethertype: IPv6
        validate_certs: False
      with_items: "{{ osp_projects }}"



    - name: configure default security group to allow ssh
      os_security_group_rule:
        auth: "{{ vars['os_auth_hailstorm_' + item.name.replace('-','_')] }}"
        security_group: "default-{{ item.name }}"
        protocol: "tcp"
        port_range_min: 22
        port_range_max: 22
        validate_certs: False
      with_items: "{{ osp_projects }}"

    - name: configure default security group to allow icmp
      os_security_group_rule:
        auth: "{{ vars['os_auth_hailstorm_' + item.name.replace('-','_')] }}"
        security_group: "default-{{ item.name }}"
        protocol: "icmp"
        validate_certs: False
      with_items: "{{ osp_projects }}"

    - name: create security group webserver in tenant demo-infra
      os_security_group:
        auth: "{{ os_auth_hailstorm_demo_infra }}"
        name: webserver
        validate_certs: False

    - name: allow HTTP in webserver security group
      os_security_group_rule:
        auth: "{{ os_auth_hailstorm_demo_infra }}"
        security_group: webserver
        protocol: "tcp"
        port_range_min: 80
        port_range_max: 80
        validate_certs: False

    - name: allow HTTPS in webserver security group
      os_security_group_rule:
        auth: "{{ os_auth_hailstorm_demo_infra }}"
        security_group: webserver
        protocol: "tcp"
        port_range_min: 443
        port_range_max: 443
        validate_certs: False


  delegate_to: localhost
