- block:
    - name: create network (in admin project)
      os_network:
        auth: "{{ os_auth_hailstorm }}"
        name: "{{ item.netname }}"
        project: admin
        shared: True
        external: true
        provider_network_type: "{% if enable_nuage is defined or current_lifecycle_env.osp_in_baremetal %}vxlan{% else %}flat{% endif %}"
        provider_physical_network: "{% if enable_nuage is not defined or current_lifecycle_env.osp_in_baremetal %}{{ item.netname }}{% endif %}"
        validate_certs: False
      with_items: "{{ overcloud_provider_networks|select|list }}"

    - name: create subnet (in admin project)
      os_subnet:
        auth: "{{ os_auth_hailstorm }}"
        name: "sub_{{ item.netname }}"
        project: admin
        enable_dhcp: False
        allocation_pool_start: "{{ item.floating_start|default(None) }}"
        allocation_pool_end: "{{ item.floating_end|default(None) }}"
        gateway_ip: "{{ item.default_gw_host_prefix | ipaddr('address') }}"
        network_name: "{{ item.netname }}"
        cidr:  "{{ item.default_gw_host_prefix | ipaddr('network') }}/{{ item.default_gw_host_prefix | ipaddr('prefix') }}"
        validate_certs: False
      with_items: "{{ overcloud_provider_networks|select|list }}"

    - name: create internal network
      os_network:
        auth: "{{ os_auth_hailstorm }}"
        name: "internal_{{ item.name }}"
        project: "{{ item.name }}"
        validate_certs: False
      with_items: "{{ osp_projects }}"
    - name: create internal sub-network
      os_subnet:
        auth: "{{ os_auth_hailstorm }}"
        name: "sub_internal_{{ item.name }}"
        network_name: "internal_{{ item.name }}"
        project: "{{ item.name }}"
        enable_dhcp: True
        dns_nameservers: "{{ infrastructure_network_guests.dns_server }}"
        gateway_ip: 172.20.0.1
        cidr:  "172.20.0.0/16"
        validate_certs: False
      with_items: "{{ osp_projects }}"

    - name: create routers
      os_router:
        auth: "{{ os_auth_hailstorm }}"
        name: "router_internal_{{ item.name }}"
        project: "{{ item.name }}"
        network: guests
        interfaces:
          - "sub_internal_{{ item.name }}"
        validate_certs: False
      register: create_router
      failed_when: "create_router|failed and 'Router already has a port on subnet' not in create_router.msg"
      with_items: "{{ osp_projects }}"


  delegate_to: localhost
