- block:
    - name: get domain user ids
      os_keystone_domain_facts:
        auth: "{{ os_auth_hailstorm }}"
        validate_certs: False

    - set_fact: hailstorm_id="{{ openstack_domains|selectattr("name", "match", "^hailstorm$")|map(attribute='id')|join("") }}"
    - name: assign admin role for projects to default domain admin
      os_user_role:
        auth: "{{ os_auth_hailstorm }}"
        domain:  "{{ hailstorm_id }}"
        user: admin
        project: "{{ item.name }}"
        role: admin
        validate_certs: False
      with_items:  "{{ osp_projects }}"


    - name: assign admin role for projects to default domain admin
      os_user_role:
        auth: "{{ os_auth_hailstorm }}"
        domain:  "{{ hailstorm_id }}"
        user: admin
        project: "{{ item.name }}"
        role: admin
        validate_certs: False
      with_items:  "{{ osp_projects }}"



    - name: assign admin users to projects
      os_user_role:
        auth: "{{ os_auth_hailstorm }}"
        user: "{{ item[1] }}"
        project: "{{ item[0].name }}"
        role: admin
        validate_certs: False
      with_nested:
        -  "{{ osp_projects }}"
        -  "{{ osp_hailstorm_domain_admin_user }}"


    - name: assign member users to projects
      os_user_role:
        auth: "{{ os_auth_hailstorm }}"
        user: "{{ item[1] }}"
        project: "{{ item[0].name }}"
        role: _member_
        validate_certs: False
      with_nested:
        -  "{{ osp_projects }}"
        -  "{{ osp_hailstorm_domain_member_user }}"
  delegate_to: localhost
