- name: set tenant quota
  os_quota: >
    {{ item.quota|combine({
      'auth': vars["os_auth_hailstorm_" + item.name|replace("-","_")],
      'validate_certs': 'False',
      'name': item.name
    }) }}
  delegate_to: localhost
  when: item.quota|default(false,true)
  with_items: "{{ osp_projects }}"
