- name: Create host aggregates configuration 
  os_nova_host_aggregate:
    auth: "{{ os_auth_hailstorm }}"
    name: "{{ item.name }}"
    availability_zone:  "{{ item.availability_zone }}"
    hosts: "{{ item.hosts }}"
    validate_certs: False
  with_items: "{{ osp_host_aggregates }}"
  delegate_to: localhost
