- name: create missing flavors
  os_nova_flavor:
    auth: "{{ os_auth_hailstorm_demo_infra }}"
    state: present
    name: "{{ item.Name }}"
    ram: "{{ item.RAM }}"
    disk: "{{ item.Disk }}"
    ephemeral: "{{ item.Ephemeral }}"
    vcpus: "{{ item.VCPUs }}"
    is_public: "{% if item['Is Public'] %}True{% else %}False{% endif %}"
    validate_certs: False
  with_items: "{{ default_overcloud_flavors }}"
  delegate_to: localhost

