- name: get existing Storage Classes
  shell: oc get storageclass |awk '!/NAME/{print $1}'
  register: storageclasses
  changed_when: false

- block:
    - name: create storageclass file
      template: src=cinder_storageclass.yaml.j2 dest=~/cinder_storageclass.yaml

    - name: create Cinder Storage Class
      shell: oc create -f ~/cinder_storageclass.yaml
  when: "'cinder' not in storageclasses.stdout_lines and cf_is_deployed_on == 'osp'"
