# Create groups in AD:
# Note: This requires Ansible 2.4 and needs to be executed against a WIN AD Host!
- name: create AD groups
  win_domain_group:
    name: "{{ item.name }}"
    description: "{{ item.desc }}"
    scope: domainlocal
    state: present
  with_items: "{{ active_directory[ inventory_hostname_short ].groups}}"
