# Create users in AD:
# Note: This requires Ansible 2.4 and needs to be executed against a WIN AD Host!
#

- name: create AD users
  win_domain_user:
    name: "{{ item.username }}"
    firstname: "{{ item.first }}"
    surname: "{{ item.last }}"
    description: "{{ item.desc }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups }}"
    state: present
  with_items: "{{ active_directory[ inventory_hostname_short ].users}}"
