# https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/11/html-single/networking_guide/#sec-lbaas
- name: Install HAproxy
  yum:
    name: haproxy
    state: present

- name: Add the LBaaS tables to the neutron database
  shell:  neutron-db-manage --subproject neutron-lbaas --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini {% if enable_nuage is defined %}--config-file /etc/neutron/plugins/nuage/plugin.ini {% endif %}upgrade head

- name: Change the service provider in neutron_lbaas.conf
  lineinfile:
    path: /etc/neutron/neutron_lbaas.conf
    line: "service_provider=LOADBALANCERV2:Haproxy:neutron_lbaas.drivers.haproxy.plugin_driver.HaproxyOnHostPluginDriver:default"
    insertafter: "^#service_provider"
    backup: yes
  notify: restart_neutron

- name: check for LBaaS v2 plugin in service_plugins under neutron.conf
  command: awk /^service_plugins=.*$/ /etc/neutron/neutron.conf
  register: check_lbaas_configured
  changed_when: False

- name: configre LBaaS v2 plugin in service_plugins under neutron.conf
  lineinfile:
    path: /etc/neutron/neutron.conf
    line: 'service_plugins=\1,neutron_lbaas.services.loadbalancer.plugin.LoadBalancerPluginv2'
    regexp: '^service_plugins=(.*)$'
    state: present
    backrefs: yes
    backup: yes
  when: not (check_lbaas_configured.stdout | search("neutron_lbaas.services.loadbalancer.plugin.LoadBalancerPluginv2"))
  notify: restart_neutron

- name: insert ovs_integration_bridge = alubr0 to [DEFAULT] section in neutron.conf
  lineinfile:
    path: /etc/neutron/neutron.conf
    line: 'ovs_integration_bridge = alubr0'
    insertafter: "^\\[DEFAULT\\]"
    regexp: '^ovs_integration_bridge'
    state: present
    backup: yes
  notify: restart_neutron
  when: enable_nuage is defined

- name: Enable Automatic Failover
  lineinfile:
    path: /etc/neutron/neutron_lbaas.conf
    line: "allow_automatic_lbaas_agent_failover=True"
    insertafter: "^#allow_automatic_lbaas_agent_failover"
    backup: yes
  notify: restart_neutron

- name: Configure lbaas_agent.ini
  lineinfile:
    path: /etc/neutron/lbaas_agent.ini
    line: "ovs_use_veth = False"
    insertafter: "^#ovs_use_veth"
    backup: yes
  notify: restart_neutron

- name: Configure lbaas_agent.ini
  lineinfile:
    path: /etc/neutron/lbaas_agent.ini
    line: "interface_driver ={% if enable_nuage is defined %}nuage_neutron.lbaas.agent.nuage_interface.NuageInterfaceDriver{% else %}neutron.agent.linux.interface.OVSInterfaceDriver{% endif %}"
    insertafter: "^#interface_driver"
    regexp: "^interface_driver"
    backup: yes
  notify: restart_neutron

- name: Configure services_lbaas.conf
  lineinfile:
    path: /etc/neutron/services_lbaas.conf
    line: "user_group = haproxy"
    insertafter: '^\[haproxy\]'
    backup: yes
  notify: restart_neutron

#- name: Disable neutron-lbaas-agent.service
#  systemd:
#    name: neutron-lbaas-agent
#    state: stopped
#    enabled: False
#    masked: True

- name: Enable and start neutron-lbaasv2-agent
  systemd:
    name: neutron-lbaasv2-agent
    state: started
    enabled: True

- name: Flush handlers
  meta: flush_handlers
