---
repos: "{{ cloudforms_repos }}"
pool_regex: "{{ cloudforms_subscription_pool_regex }}"
packages: git
packages_uninstall: cloud-init
ntp_client: will_be_configured_in_the_cf_config_role

cfme_settings2:
  ":server": '{:timezone=>"Berlin", :company=>"Hailstorm", :role=>"{{ cf_roles }}"}'
  ":smtp": '{:authentication=>"none", :domain=>"{{ hailstorm_dns_domain }}", :from=>"cloudforms@{{ hailstorm_dns_domain }}", :host=>"{{ hostvars["infrastructure"].hostname }}", :password=>"", :port=>"25", :user_name=>"evmadmin" }'
  ":authentication": '{:mode=>"httpd", :local_login_disabled=>false, :saml_enabled=>{% if cf_use_rhsso|default(false,true) %}true{% else %}false{% endif %}, :sso_enabled=>{% if cf_use_rhsso|default(false,true) %}true{% else %}false{% endif %}, :user_proxies=>[{}], :httpd_role=>true, :amazon_role=>false, :ldap_role=>false }'
  ":ntp": '{:server=>["{{ infrastructure_address_ntp_server }}"]}'

tdagent_configs:
  - tag: evm.log
    path: /var/www/miq/vmdb/log/evm.log
    pos_file: /var/log/td-agent/evm_log.pos
    format: multiline
    format_firstline: '/^\[----\].*/'
    format1: '/^\[----\]\ [A-Z],\ \[(?<time>[^\ ]*)\ #(?<pid>[0-9]*):(?<thread>[\h]*)\]\s+(?<loglevel>[A-Z]*)\ --\ :(?<message>.*)/'
    time_format: "%Y-%m-%dT%H:%M:%S.%N"
    permissions:
      - path: /var/www/miq/vmdb/log/evm.log
        mode: o+xr
