---
ose_management_infra_project: management-infra
ose_cfme_serviceaccount_name: management-admin

mem: "{{ layer2_ose3node_mem }}"
vcpu: "{{ layer2_ose3node_cpu }}"

disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 60
  format: qcow2
  # partition_table:
  #   lvmpv: 29500
  #   swap: 2048
  #   home: 2048
  #   root: 10000

  physvols:
    boot: 500
    rhel: 59500
  logvols:
    - name: swap
      fstype: swap
      mountpoint: swap
      size: 2048
    - name: root
      fstype: "{{ fstype }}"
      mountpoint: /
      size: 5120
    - name: home
      fstype: "{{ fstype }}"
      mountpoint: /home
      size: 2048
    - name: var
      fstype: "{{ fstype }}"
      mountpoint: /var
      size: 40720


openshift_master_api_host_and_port: openshift.{{ hailstorm_dns_domain }}:443

vm_secgroups:
  - "master-{{ ocp_tenant }}"
  - "appnode-{{ ocp_tenant }}"

pool_regex: "{{ osp_infra_subscription_pool_regex }}"
