# the fact "osp_internal_ip" is set by the layer3_vm_on_openstack role

- block:
    - name: create /etc/hosts entries
      lineinfile:
        dest: /etc/hosts
        line: "{{ hostvars[item].osp_internal_ip }} {{ item }} {{ item }}.{{ hailstorm_dns_domain }}{% for name in (hostvars[item].additional_dns|default('')).split(',') %}{% if name != '' and name[0] != '*' %} {{ name }} {{ name }}.{{ hailstorm_dns_domain }}{% endif %}{% endfor %}"
        regexp: "{{ hostvars[item].osp_internal_ip }} {{ item }} {{ item }}\\.{{ hailstorm_dns_domain }}.*$"
      when: hostvars[item].osp_internal_ip|default('') != ''
      with_items: "{{ group }}"


    - name: create /etc/cloud/templates/hosts.redhat.tmpl entries
      lineinfile:
        dest: /etc/cloud/templates/hosts.redhat.tmpl
        line: "{{ hostvars[item].osp_internal_ip }} {{ item }} {{ item }}.{{ hailstorm_dns_domain }}{% for name in (hostvars[item].additional_dns|default('')).split(',') %}{% if name != '' and name[0] != '*' %} {{ name }} {{ name }}.{{ hailstorm_dns_domain }}{% endif %}{% endfor %}"
        regexp: "{{ hostvars[item].osp_internal_ip }} {{ item }} {{ item }}\\.{{ hailstorm_dns_domain }}.*$"
      when: hostvars[item].osp_internal_ip|default('') != ''
      with_items: "{{ group }}"
  when: mode=="create"

# - block:
#   when: mode=="destroy"
