# - name: create nuage repo directory on satellites web server
#   file:
#     path: /var/www/html/pub/{{ satellite_www_dir }}
#     state: directory
#     owner: root
#     group: root
#     mode: 0755

# - name: create repo file
#   template:
#     src: ../templates/nuage.repo.j2
#     dest: /var/www/html/pub/nuage/nuage.repo
#     owner: root
#     group: root
#     mode: 0744

- name: ensure that root has an ssh key set
  user: name=root generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
  delegate_to: "{{ infrastructure_delegate_local_content_host }}"

- name: read layer1 root ssh pub key
  shell: cat /root/.ssh/id_rsa.pub
  register: layer1_ssh_pub_key
  delegate_to: "{{ infrastructure_delegate_local_content_host }}"
  changed_when: false

- name: add layer1 root ssh pub key to rhosp-director
  authorized_key: user=root key={{ layer1_ssh_pub_key.stdout }}

- name: create target directory on satellites web server
  file:
    path: /var/www/html/pub/{{ satellite_www_dir }}/{{ item|regex_replace('(.*)/.+','\1') }}
    state: directory
    owner: root
    group: root
    mode: 0755
  when: "'/' in item"
  with_items: "{{ installables }}"

- name: copy installables from layer1
  synchronize: mode=push src={{ layer1_binary_dir }}/{{ item }} dest=/var/www/html/pub/{{ satellite_www_dir }}/{{ item }}
  delegate_to: "{{ infrastructure_delegate_local_content_host }}"
  with_items: "{{ installables }}"
