- block:
    - name: Configure rsyslog
      lineinfile:
        path: /etc/rsyslog.conf
        #line: "*.* @{{ (hostvars[item].vm_nics|selectattr('netname','match', infrastructure_network_services.netname)|first).ip }}:514"
        line: "*.* @{{ hostvars[item].hostname }}:514"
        regexp: ^\*\.\* @.*:514
        insertafter: "#### RULES ####"
      register: configure_syslog
      when: '"syslog" in hostvars[item].roles'
      with_items: "{{ groups['infrastructure-group'] }}"
    - name: Restart rsyslog
      service: name=rsyslog state=restarted
      when: configure_syslog|changed
  when: mode=="create"
