- block:
    - include: create.yml
      tags: ["installhost-create"]
    - include: sync_and_continue.yml
      tags: ["installhost-sync"]
  when: mode=="create"

- block:
    - include: destroy.yml
      tags: ["installhost"]
  when: mode=="destroy"
