- name: get your username
  command: whoami
  register: whoami
  delegate_to: localhost
  changed_when: false

- fail: msg="Don't work with root user!!"
  when: whoami.stdout == "root"

- name: Synchronize current directory to install-host
  synchronize:
    src=../../../../
    dest=/root/hailstorm-{{ whoami.stdout }}/
    use_ssh_args=True

- get_argv:


- name: Continuing the installation using install host
  command: tmux  new-session -s ansible-{{ whoami.stdout }} -d "ANSIBLE_HOST_KEY_CHECKING=False {{ argv | join(' ') }};bash -i"
  args:
    chdir: "/root/hailstorm-{{ whoami.stdout }}/ansible/"
  when: current_lifecycle_env.use_install_host==True
