- name: Enable and start httpd
  service:
    name: httpd
    state: started
    enabled: True

- name: Write a sample index.html
  copy:
    dest: /var/www/html/index.html
    content: "Hello from {{ ansible_host }}"

- block:
    - name: Show ips
      debug: var=hostvars[inventory_hostname_short]["openstack_servers"][0].private_v4
    - name: List load balancers
      shell:  . ~/overcloudrc_v3 && neutron lbaas-loadbalancer-list -f json
      run_once: true
      register: list_lb
      changed_when: False

    - block:
        - name: Create load balancer
          shell: . ~/overcloudrc_v3 && neutron lbaas-loadbalancer-create -f json --name lbaas-demo-osp-lb "sub_internal_{{ osp_tenant }}"
          run_once: true
          register: create_lb
        
        - set_fact: vip_port_id="{{ (create_lb.stdout|from_json).vip_port_id }}"
          run_once: true

        - name: Wait some seconds to finish the creation
          pause:
            seconds: 3

        - name: Assign security group webserver to the load balancer
          shell: . ~/overcloudrc_v3 && neutron port-update --security-group webserver "{{ vip_port_id }}"

        - name: Create listener
          run_once: true
          shell: . ~/overcloudrc_v3 && neutron lbaas-listener-create --name lbaas-demo-osp-lb-listener --loadbalancer lbaas-demo-osp-lb --protocol HTTP --protocol-port 80
        - name: Wait some seconds to finish the creation
          pause:
            seconds: 3

        - name: Create pool
          run_once: true
          shell: . ~/overcloudrc_v3 && neutron lbaas-pool-create --name lbaas-demo-osp-lb-pool  --lb-algorithm ROUND_ROBIN --listener lbaas-demo-osp-lb-listener --protocol HTTP
        - name: Wait some seconds to finish the creation
          pause:
            seconds: 10

        - name: Add the members
          shell: . ~/overcloudrc_v3 && neutron lbaas-member-create --subnet sub_internal_{{ osp_tenant }} --address "{{  hostvars[inventory_hostname_short]["openstack_servers"][0].private_v4 }}" --protocol-port 80 lbaas-demo-osp-lb-pool

        - name: Create the floating IP for the load balancer
          shell:  . ~/overcloudrc_v3 &&  openstack floating ip create -f json --port {{ vip_port_id }} guests
          register: create_fip
          run_once: true

        - set_fact: fip="{{ (create_fip.stdout|from_json).floating_ip_address }}"
        - name: Wait some seconds to finish the creation
          pause:
            seconds: 3

        - name: Access to the floating IP for the load balancer 
          uri: 
            url: "http://{{ fip }}"
            return_content: yes
          register: try
        - debug: var=try.content

      when: '"lbaas-demo-osp-lb" not in (list_lb.stdout|from_json)|map(attribute="name")  | list'


  become_user: "{{ hostvars['rhosp-director'].rhosp_stack_user }}"
  become: True
  delegate_to: rhosp-director
