- block:
  - name: List load balancers
    shell:  . ~/overcloudrc_v3 && neutron lbaas-loadbalancer-show lbaas-demo-osp-lb -f json
    run_once: true
    register: list_lb
    failed_when: False
    changed_when: False
  - block:

    - name: Obtain the floating IP for the load balancer
      shell: . ~/overcloudrc_v3 && openstack floating ip list -f json  --fixed-ip-address {{ (list_lb.stdout|from_json).vip_address }}
      register: floating_ip

    - name:  Delete the floating IP for the load balancer
      shell:  . ~/overcloudrc_v3 &&  openstack floating ip delete {{ (floating_ip.stdout | from_json | first)["Floating IP Address"] }}
      register: create_fip
      run_once: True
      when: floating_ip.stdout != '[]'
 
    - name: Delete the pool for the load balancer
      shell: . ~/overcloudrc_v3 &&  neutron lbaas-pool-delete lbaas-demo-osp-lb-pool
      run_once: True

    - name: Delete the listener for the load balancer
      shell: . ~/overcloudrc_v3 && neutron lbaas-listener-delete lbaas-demo-osp-lb-listener
      run_once: True

    - name: Delete the load balancer
      shell: . ~/overcloudrc_v3 && neutron lbaas-loadbalancer-delete lbaas-demo-osp-lb
      run_once: True

    when: list_lb.rc == 0
  become_user: "{{ hostvars['rhosp-director'].rhosp_stack_user }}"
  become: True
  delegate_to: rhosp-director




