---
# #!/bin/sh
# # Install Splunk forwarder on Unix to run als local user "splunk"
# # and connect to deployment server (see configuration of MY_DEPLOYMENT_SERVER)
#
# # You may change configuration at next line:
# MY_DEPLOYMENT_SERVER=si0vm1988.de.bosch.com
#
# if [ x`whoami` != xroot ]; then
#   echo Stop\: This script must run as root!
#   exit
# fi
#
# # Needed for Splunk_TA_nix:
# yum -y install sysstat
#
# echo "Install Splunk forwarder .."
# rpm -Uvh http://rb-itoa.de.bosch.com/etc/splunkforwarder-latest-linux-2.6-x86_64.rpm
# su - splunk -c "splunk start --accept-license"
# su - splunk -c "splunk set deploy-poll ${MY_DEPLOYMENT_SERVER}:8089 -auth admin:changeme"
# /opt/splunkforwarder/bin/splunk enable boot-start -user splunk
# su - splunk -c "splunk edit user admin -password `date +%s | sha256sum | base64 | head -c 32` -auth admin:changeme"
# service splunk restart
#
# exit


- block:
    # - name: copy over the splunk installation
    #   copy: src=binary/{{ current_lifecycle_env.splunk_agent_rpm }} dest=/tmp

    - name: install splunk with yum
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - sysstat
        - "{{ splunk_agent_rpm_url }}"

    - name: splunk license
      command: /opt/splunkforwarder/bin/splunk start --accept-license creates=/opt/splunkforwarder/etc/users/splunk-system-user
      register: splunk_license

    - name: connect to splunk server
      command: /opt/splunkforwarder/bin/splunk -c "splunk set deploy-poll {{ splunk_agent_server }}:{{ splunk_agent_port|default('8089') }} -auth {{ splunk_agent_user|default('admin') }}:{{ splunk_agent_password|default('changeme') }}"
      when: splunk_license|changed

    - name: setup to start at boot
      command: /opt/splunkforwarder/bin/splunk enable boot-start -user splunk
      when: splunk_license|changed

    - name: add monitor for /var/log
      command: /opt/splunkforwarder/bin/splunk add monitor /var/log
      when: splunk_license|changed

    - name: change splunk admin password
      shell: /opt/splunkforwarder/bin/splunk -c "splunk edit user {{ splunk_agent_user|default('admin') }} -password `date +%s | sha256sum | base64 | head -c 32` -auth {{ splunk_agent_user|default('admin') }}:{{ splunk_agent_password|default('changeme') }}"
      when: splunk_license|changed

    - name: restart splunk service
      service: name=splunk state=restarted
      when: splunk_license|changed
      
    # - name: connect to splunk server
    #   command: /opt/splunkforwarder/bin/splunk add forward-server {{ splunk_agent_server }}:{{ splunk_agent_port|default('8089') }} -auth {{ splunk_agent_user }}:{{ splunk_agent_password }}

  when: splunk_agent_server|default(false, true) and splunk_agent_rpm_url|default(false, true)
