- block:
    - include: roles/common/tasks/prepare_nfs_export.yml
      vars:
        items:
          - path: "{{ layer1_binary_dir }}"
        export_params: "(ro)"
  when: mode=="create"

- block:
    - include: roles/common/tasks/remove_nfs_export.yml
      vars:
        items:
          - path: "{{ layer1_binary_dir }}"
  when: mode=="destroy"
