- name: check replicationcontrollers in default ns
  command: oc get rc -n default
  register: rc
  changed_when: false

- name: deploy router
  command: oadm router router --replicas=1 \
           --credentials='/etc/origin/master/openshift-router.kubeconfig' \
           --service-account=router
  when: "'router' not in rc.stdout"

#registry is deployed via ansible playbook with OSCP3.3
- name: deploy registry
  command: >
    oadm registry
    --replicas=1
    --config=/etc/origin/master/admin.kubeconfig
    --credentials=/etc/origin/master/openshift-registry.kubeconfig
    --images='registry.access.redhat.com/openshift3/ose-${component}:${version}'
  when: "'docker-registry' not in rc.stdout"

- name: check existing pvc
  shell: oc get pvc -n default
  register: pvc
  changed_when: false

- name: create pvc
  shell: "oc create -f - <<EOF
         {{ lookup('template','pvc.yaml.j2') }}"
  with_items:
    - name: docker-registry
      size: 5Gi
      accessmode: ReadWriteOnce
      #TODO - change back to ReadWriteMany when other storage classes are avialable
  when: "'docker-registry' not in pvc.stdout"

- name: add pvc to registry
  command: oc -n default volume deploymentconfigs/docker-registry --add --name=registry-storage -t pvc --claim-name=docker-registry --overwrite
  when: "'docker-registry' not in pvc.stdout"
