- name: make ifcfg files in the vm
  template: src=ifcfg-device.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{ item.dev }}
  with_items: "{{ vm_nics }}"
  register: ifcfg

- name: make rule files in the vm
  template: src=rule-device.j2 dest=/etc/sysconfig/network-scripts/rule-{{ item.dev }}
  when: item.dev != "eth0"
  with_items: "{{ vm_nics }}"
  register: rule

- name: make route files in the vm
  template: src=route-device.j2 dest=/etc/sysconfig/network-scripts/route-{{ item.dev }}
  when: item.dev != "eth0"
  with_items: "{{ vm_nics }}"
  register: route

- name: make rt_tables file in the vm
  template: src=rt_tables.j2 dest=/etc/iproute2/rt_tables
  register: rt_tables

- name: enable interfaces
  shell: ifup {{ item.dev }}
  with_items: "{{ vm_nics }}"
  when: ifcfg|changed or rule|changed or route|changed or rt_tables|changed
