- name: check for work here already done
  stat: path=/usr/share/openstack-tripleo-heat-templates/puppet/extraconfig/pre_deploy/compute/nova-nuage.yaml
  register: patch_rhosp_for_nuage_done

- block:
    - name: patch RHOSP with nuages patchfile
      patch:
        src: diff_OSPD11_6.2.0-3
        basedir: /usr/share

    - name: copy over missing nova-nuage.yaml file
      copy:
        src: /home/{{ rhosp_stack_user }}/nuage-ospdirector-ML2-SRIOV/openstack-tripleo-heat-templates/puppet/extraconfig/pre_deploy/compute/nova-nuage.yaml
        dest: /usr/share/openstack-tripleo-heat-templates/puppet/extraconfig/pre_deploy/compute
        remote_src: yes
  when: patch_rhosp_for_nuage_done.stat.exists == False
