- block:
    - name: install docker
      yum: name={{ ose3_additional_packages }} state=present
    - name: Copy the docker file to the hosts
      template:
        src: docker.j2
        dest: /etc/sysconfig/docker-storage-setup
    - name: Block docker.io registry
      lineinfile:
        dest: /etc/containers/registries.conf
        insertafter: 'EOF'
        line: '{{item}}'
      with_items:
      - 'block_registries:'
      - '  - docker.io'
    - name: ensure docker is running
      service: name=docker state=started enabled=yes
    # - name: remove DNS2 config from ifcfg-eth0
    #   lineinfile: regexp="^DNS2=.*" state=absent dest=/etc/sysconfig/network-scripts/ifcfg-eth0

    - name: check docker daemon proxy settings
      shell: grep -E '{{ item.regexp }}' /etc/sysconfig/docker || true
      changed_when: false
      with_items:
        - line: HTTP_PROXY='{{ http_proxy.protocol }}://{% if http_proxy.username is defined %}{{ http_proxy.username }}{% if http_proxy.password is defined %}:{{ http_proxy.password }}{% endif %}{% endif %}@{{ http_proxy.proxyname }}{% if http_proxy.port is defined %}:{{ http_proxy.port }}{% endif %}'
          regexp: ^HTTP_PROXY=.*
        - line: HTTPS_PROXY='{{ http_proxy.protocol }}://{% if http_proxy.username is defined %}{{ http_proxy.username }}{% if http_proxy.password is defined %}:{{ http_proxy.password }}{% endif %}{% endif %}@{{ http_proxy.proxyname }}{% if http_proxy.port is defined %}:{{ http_proxy.port }}{% endif %}'
          regexp: ^HTTPS_PROXY=.*
        - line: NO_PROXY=.{{ hailstorm_dns_domain }}
          regexp: ^NO_PROXY=.*
      register: temp_docker_proxy_config

    - name: configure docker daemon proxy settings
      lineinfile: dest=/etc/sysconfig/docker line={{ item.item.line }} regexp={{ item.item.regexp }}
      with_items: '{{ temp_docker_proxy_config.results }}'
      when: item.stdout == ""
      register: temp_docker_new_proxy_config

    - name: restart docker
      service: name=docker state=restarted
      when: temp_docker_new_proxy_config|changed

  when: mode=="create"
