- block:
    - name: configure BIND to listen on eth0
      lineinfile: line="  listen-on port 53 { 127.0.0.1; {{ vm_nics[0].ip }}; };" regexp=".*listen-on port 53.*" dest=/etc/named.conf
    - name: configure BIND not to listen on ipv6
      lineinfile: line='OPTIONS="-4"' dest=/etc/sysconfig/named
    - name: configure BIND to answer external queries
      lineinfile: line="  allow-query     { any; };" regexp=".*allow-query.*" dest=/etc/named.conf
    - name: create zone db directory
      file: state=directory path=/etc/named/zones/master
    - name: create a sensible serial for BIND zone
      shell: date +%Y%m%d$((`date +%-H`*4+`date +%-M`/8))
      register: bind_zone_serial
    - name: create zone db
      template: src=zone.db.j2 dest=/etc/named/zones/master/db.{{ hailstorm_dns_domain }}
    - name: add zone db to bind config
      lineinfile: line="zone \"{{ hailstorm_dns_domain }}\" { type master; file \"/etc/named/zones/master/db.{{ hailstorm_dns_domain }}\"; };" dest=/etc/named.rfc1912.zones
    - name: ensure that named is restarted
      service: name=named enabled=yes state=restarted

  when: mode=="create" and external_network_config.services_network_dnat is defined

- block:
    - name: create a sensible serial for BIND zone
      shell: date +%Y%m%d$((`date +%-H`*4+`date +%-M`/8))
      register: bind_zone_serial
    - name: add or change host in zone db
      lineinfile:
        dest: "/etc/named/zones/master/db.{{ hailstorm_dns_domain }}"
        line: "{{ item.name }} 				IN      A       {{ item.ip }}"
        regexp: "^{{ item.name|regex_escape }}.*"
      with_items: >
        [{% set needscomma = [false] %}{% for host in group %}
        {% for name in ((hostvars[host].additional_dns|default('')).split(',') + [host]) %}
        {% if hostvars[host].floating_ip|default('') != '' %}
        {% if needscomma|last %},{% endif %}
        {"name": "{{ name }}", "ip": "{{ hostvars[host].floating_ip}}" }
        {% if needscomma.append(true) %}{% endif %}
        {% endif %}
        {% endfor %}
        {% endfor %}]
    - name: change serial in zone db
      lineinfile:
        dest: "/etc/named/zones/master/db.{{ hailstorm_dns_domain }}"
        line: "                          {{ bind_zone_serial.stdout }}        ; Serial"
        regexp: ".*; Serial$"
    - name: ensure that named is restarted
      service: name=named enabled=yes state=restarted
  when: mode=="floating_ip"

- block:
    - name: create a sensible serial for BIND zone
      shell: date +%Y%m%d$((`date +%-H`*4+`date +%-M`/8))
      register: bind_zone_serial
    - name: add or change host in zone db
      lineinfile:
        dest: "/etc/named/zones/master/db.{{ hailstorm_dns_domain }}"
        line: "{{ item }} 				IN      A       {{ lbip }}"
        regexp: "^{{ item|regex_escape }} .*"
      with_items: "{{ lbdnsname }}"
    - name: change serial in zone db
      lineinfile:
        dest: "/etc/named/zones/master/db.{{ hailstorm_dns_domain }}"
        line: "                          {{ bind_zone_serial.stdout }}        ; Serial"
        regexp: ".*; Serial$"
    - name: ensure that named is restarted
      service: name=named enabled=yes state=restarted
  when: mode=="lbaas_ip"
