---
#### SATELLITE ####
# refresh subscription to include the "guests of"... subscriptions
- hosts: satellite
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_satellite, tags: [ 'layer2', 'satellite' ], mode: refresh_subscriptions }


#### TOWER ####

- hosts: ansible-jump-host
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer3_vm_on_openstack, tags: [ 'layer3', 'vm', 'tower', 'tower-inventory-l3', 'tower-inventory-l3-openstack', 'vm'], mode: create }
    - { role: layer2_rhel, tags: [ 'layer3', 'tower', 'rhel', 'tower-inventory-l3', 'tower-inventory-l3-openstack', 'rhel'], mode: create, when: "vm_exists is defined and vm_exists == true"}


- hosts: tower
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_ansibletower_l3inventory, tags: [ 'layer2', 'tower', 'tower-inventory-l3', 'tower-inventory-l3-cloudforms' ], mode: create, kind: "cloudforms", inventoryname: "Hailstorm", groupname: "CloudForms", credentialname: "Hailstorm L3 SSH", cloud_credentials: {"username":"admin", "password":"{{ root_password }}", "url":"https://{{ hostvars[openstack_vip|default('openstack')].hostname }}"} }
    - { role: layer2_ansibletower_l3inventory, tags: [ 'layer2', 'tower', 'tower-inventory-l3', 'tower-inventory-l3-openstack' ], mode: create, kind: "openstack", inventoryname: "Hailstorm", groupname: "OpenStack", credentialname: "Hailstorm L3 SSH", cloud_credentials: {"username":"admin", "password":"{{ root_password }}", "url":"http://{{ hostvars[openstack_vip|default('openstack')].hostname }}:5000/v3", "project": "demo-vms", "domain": "hailstorm"}, "jumphost": "{{ hostvars['ansible-jump-demo-vms'].ansible_host }}" }
#    - { role: layer2_ansibletower_inventory, tags: [ 'layer2', 'tower', 'tower-openstack' ], mode: create, kind: "openstack", inventoryname: "Hailstorm L3", groupname: "OpenStack Infra-VMs", cloud_credentials: {"username":"admin", "password":"{{ root_password }}", "url":"http://openstack.{{ hailstorm_dns_domain }}:5000/v3", "project": "demo-infra", "domain": "hailstorm"}, "jumphost": "{{ hostvars['ansible-jump-demo-infra'].ansible_host }}" }
