---
#### Infrastructure (DNS, SMTP/IMAP) ####

- hosts: infrastructure-group
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'infrastructure', 'vm' ], mode: create }
    - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer2', 'infrastructure', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
    - { role: layer2_rhel, tags: [ 'layer2', 'infrastructure', 'rhel' ], mode: create }
    - { role: layer2_dnat_dns, tags: [ 'layer2', 'infrastructure', 'dnat' ], mode: create, when: '"dnat" in hostvars[inventory_hostname_short].roles'  }
    - { role: layer2_smtp_imap, tags: [ 'layer2', 'infrastructure', 'smtp'], mode: create, when: '"smtp" in hostvars[inventory_hostname_short].roles' }
    - { role: layer2_ntp, tags: [ 'layer2', 'infrastructure', 'ntp'], mode: create, when: '"ntp" in hostvars[inventory_hostname_short].roles' }
    - { role: layer2_syslog, tags: [ 'layer2', 'infrastructure', 'syslog'], mode: create, when: '"syslog" in hostvars[inventory_hostname_short].roles' }
    - { role: layer2_tdagent, tags: [ 'layer2', 'tdagent', 'infrastructure'], mode: create }
#    - { role: layer2_haproxy_service, tags: [ ''layer2', 'infrastructure', 'haproxy' ], mode: create,  when: '"haproxy" in hostvars[inventory_hostname_short].roles' }

#### VIRT-WHO host (either infrastrcture or satellite)

- hosts: virt-who
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_virtwho, tags: [ 'layer2', 'virtwho' ], mode: create }

#### BOSCH VPN Client

- hosts: bosch-vpn-group
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'bosch-vpn', 'vm'], mode: create }
    - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer2', 'bosch-vpn', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
    - { role: layer2_rhel, tags: [ 'layer2', 'bosch-vpn', 'rhel' ], mode: create }
    - { role: layer2_cisco_anyconnect_client, tags: [ 'layer2', 'bosch-vpn', 'anyconnect' ], mode: create }


- hosts: efk
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'efk', 'vm' ], mode: create }
    - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer2', 'efk', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
    - { role: layer2_rhel, tags: [ 'layer2', 'efk', 'rhel'], mode: create }
    - { role: layer2_efk_rhosp_optools, tags: [ 'layer2', 'efk', 'efk-install'], mode: create, when: "current_lifecycle_env.openstack_version < 10" }
    - { role: layer2_ipa_certificate, tags: ['layer2', 'efk', 'efk-certificate'], mode: create, when: "current_lifecycle_env.openstack_version >= 10" }
    - { role: layer2_efk_centos_opstools, tags: [ 'layer2', 'efk', 'efk-install'], mode: create, when: "current_lifecycle_env.openstack_version >= 10" }
