---

- hosts: ose3-osp
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer3_vm_on_openstack, tags: [ 'layer3', 'ose3-osp', 'vm' ], mode: create }
    - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer3', 'ose3-osp', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
    - { role: layer2_rhel, tags: [ 'layer3', 'ose3-osp', 'rhel' ], mode: create }
    - { role: layerX_distribute_pubkey, tags: [ 'layer3', 'ose3-osp', 'ose3-osp-installprep' ], mode: create, pubkeyhost: ose3-osp-master1 }
    - { role: layerX_ipa_client, tags: [ 'layer3', 'ose3-osp',  'ipa-client'], mode: create }

- hosts: ose3-osp-common
  remote_user: root
  gather_facts: false
  roles:
    - { role: layerX_openshift_osp_node, tags: [ 'layer3', 'ose3-osp', 'ose3-osp-node' ], mode: create }

- hosts: ose3-osp-installer
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_ipa_certificate, tags: ['layer3', 'ose3-osp', 'ose3-osp-install', 'ose3-roles'], mode: create, certcn: 'openshift-osp.{{ hailstorm_dns_domain }}', factprefix: openshift }
    - { role: layer2_rhsso_client, tags: ['layer3', 'ose3-osp', 'ose3-osp-install', 'ose3-oidc'], mode: create, oidcClientName: 'ocp-osp-master',  oidcRedirect: 'https://openshift-osp.{{ hailstorm_dns_domain }}/*', factprefix: ocpOidcClient }
    - { role: layerX_openshift_installer_on_openstack, tags: [ 'layer3', 'ose3-osp', 'ose3-osp-install', 'ose3-metrics', 'ose3-roles' ], mode: create }
    - { role: layer2_ipa_certificate, tags: ['layer3', 'ose3-osp', 'ose3-osp-install', 'ose3-logging-certificate'], mode: create, certcn: 'kibana.{{ ocp_apps_dns_domain }}' }
    - { role: layerX_openshift_route_certificate, tags: ['layer3', 'ose3-osp', 'ose3-osp-install', 'ose3-logging-certificate'], mode: create, route: "logging-kibana", namespace: "logging" }
    - { role: layer2_ipa_certificate, tags: ['layer3', 'ose3-osp', 'ose3-osp-install', 'ose3-metrics-certificate'], mode: create, certcn: 'hawkular-metrics.{{ ocp_apps_dns_domain }}' }
    - { role: layerX_openshift_route_certificate, tags: ['layer3', 'ose3-osp', 'ose3-osp-install', 'ose3-metrics-certificate'], mode: create, route: "hawkular-metrics", namespace: "openshift-infra" }
    - { role: layer2_ipa_certificate, tags: ['layer3', 'ose3-osp', 'ose3-osp-install', 'ose3-router-certificate'], mode: create, certcn: '{{ ocp_apps_dns_domain }}', wildcard: true, factprefix: wildcard }
    - { role: layerX_openshift_router_wildcardcertificate, tags: ['layer3', 'ose3-osp', 'ose3-osp-install', 'ose3-router-certificate'], mode: create }

- hosts: ose3-osp-installer
  remote_user: root
  gather_facts: false
  roles:
    - { role: layerX_openshift_devops_tools, tags: [layer3, 'ose3-osp', 'ose3-devops'], mode: create }

- hosts: ose3-osp-lb
  remote_user: root
  gather_facts: false
  roles:
    - { role: layerX_openshift_lb, tags: [ 'layer3', 'ose3-osp', 'ose3-osp-install','ose3-osp-lb' ], mode: create }
