---
- hosts: primary-ad-group
  remote_user: root
  gather_facts: false
  roles:
     - { role: layer2_active_directory, tags: [ 'layer2', 'ad', 'vm' ], mode: setmx }

- hosts: windows-group
  remote_user: root
  gather_facts: false
  roles:
     - { role: layer2_active_directory, tags: [ 'layer2', 'ad', 'groups' ], mode: groups }
     - { role: layer2_active_directory, tags: [ 'layer2', 'ad', 'users' ], mode: users }
