#### RH-SSO
# ansible-playbook -i hosts -e @config/infrastructure_config.yml -e @config/hailstorm_config.yml -e @config/storm3.coe.muc.redhat.com.yml create-01-base.yml --tags rh-sso

- hosts: rh-sso-l2-vm-group
  remote_user: root
  gather_facts: false
  roles:
    - role: layer2_vms
      tags: [ 'layer2', 'rhsso', 'vm' ]
      mode: create

- hosts: rh-sso-osp-vm-group
  remote_user: root
  gather_facts: false
  roles:
    - role: layer3_vm_on_openstack
      tags: [ 'layer3', 'rhsso', 'vm' ]
      mode: create

- hosts: rh-sso-group
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer2', 'rhsso', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
    - { role: layer2_rhel, tags: [ 'layer2', 'rhsso', 'rhel' ], mode: create }
    - { role: layerX_ipa_client, tags: [ 'layer2', 'rhsso',  'ipa-client'], mode: create }
    - { role: layer2_ipa_certificate, tags: ['layer2', 'rhsso', 'rhsso-cert', 'rhsso-install'], mode: create, certcn: 'sso.{{ hailstorm_dns_domain }}', factprefix: rhsso }
    - { role: layer2_rhsso, tags: [ 'layer2', 'rhsso', 'rhsso-install' ], mode: create }
