---
#### install-host
- hosts: install-host
  remote_user: root
  gather_facts: false
  roles:
    - role: layer2_nuage
      tags: [ 'layer2', 'nuage' ]
      mode: create


- hosts: infrastructure-group
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_ipa_certificate, tags: ['layer2', 'infrastructure',  'nuage', 'haproxy', 'haproxy-certificate'], mode: create, certcn: 'vsd.{{ hailstorm_dns_domain }}' }
    - role: layer2_haproxy_service
      tags: [ 'layer2', 'infrastructure', 'nuage', 'haproxy' ]
      mode: create
      haproxy_listen_port: 443
      haproxy_listen_ip: "{{ (hostvars['infrastructure'].vm_nics|selectattr('netname','match',infrastructure_network_services.netname)|first).ip }}"
      haproxy_listen_proto: "https"
      haproxy_connect_port: 8443
      haproxy_hostgroup: "nuage-vsd"
      haproxy_name: "nuage_vsd"
      when: '"haproxy" in hostvars[inventory_hostname_short].roles'
      balance: source
    - role: layer2_haproxy_service
      tags: [ 'layer2', 'infrastructure', 'nuage', 'haproxy' ]
      mode: create
      haproxy_listen_port: 9200
      haproxy_listen_ip: "{{ (hostvars['infrastructure'].vm_nics|selectattr('netname','match',infrastructure_network_services.netname)|first).ip }}"
      haproxy_listen_proto: "http"
      haproxy_connect_port: 9200
      haproxy_hostgroup: "nuage-elastic"
      haproxy_name: "nuage_elastic"
      when: '"haproxy" in hostvars[inventory_hostname_short].roles'


#

#### director
# moved to create-03-osp.yml
#- hosts: rhosp-director
#  remote_user: root
#  gather_facts: false
#  roles:
#    - role: layer2_rhosp_undercloud_configure_nuage
#      tags: ['layer2', 'nuage', 'undercloud-config-nuage']
#      mode: create
