---
#### CEPH

- hosts: ceph
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'ceph', 'vm' ], mode: create }
    - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer2', 'ceph', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
    - { role: layer2_rhel, tags: [ 'layer2', 'ceph', 'rhel' ], mode: create }
    - { role: layerX_distribute_pubkey, tags: [ 'layer2', 'ceph', 'ceph-installprep' ], mode: create, pubkeyhost: ceph0 }

- hosts: ceph-installer
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_ceph_installer, tags: [ 'layer2', 'ceph', 'ceph-install', 'ceph-installer' ], mode: create }

- hosts: ceph-calamari
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_ceph_calamari, tags: [ 'layer2', 'ceph', 'ceph-install', 'ceph-calamari' ], mode: create }

- hosts: ceph-rgws-installer
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_ceph_rgw_installer, tags: [ 'layer2', 'ceph', 'ceph-install', 'ceph-rgws' ], mode: create }

# - hosts: storage-console
#   remote_user: root
#   gather_facts: false
#   roles:
#     - { role: layer2_vms, tags: [ 'layer2', 'storage-console', 'vm' ], mode: create }
#     - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer2', 'storage-console', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
#     - { role: layer2_rhel, tags: [ 'layer2', 'storage-console', 'rhel' ], mode: create }
#     - { role: layer2_ipa_certificate, tags: ['layer2', 'storage-console', 'cert' ], mode: create }
#     - { role: layer2_storageconsole, tags: [ 'layer2', 'storage-console', 'storage-console-install' ], mode: create }


# create the "nuage" VMs, subscribe against satellite,
# install packages defined in groups/newgroup.yml and
# register IPA client
# ansible-playbook -i hosts -e @config/infrastructure_config.yml -e @config/hailstorm_config.yml -e @config/storm3.coe.muc.redhat.com.yml create-01-base.yml --tags nuage
# - hosts: nuage
#   remote_user: root
#   gather_facts: false
#   roles:
#     - role: layer2_vms
#       tags: [ 'layer2', 'nuage', 'vm' ]
#       mode: create
#     - role: layer2_rhel_reconfigure_dns
#       tags: [ 'layer2', 'nuage', 'dns' ]
#       mode: create
#       nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}"
#     - role: layer2_rhel
#       tags: [ 'layer2', 'nuage', 'rhel' ]
#       mode: create
#     - role: layerX_ipa_client
#       tags: [ 'layer2', 'nuage',  'ipa-client']
#       mode: create
