---
- hosts: layer1-group
  remote_user: root
  gather_facts: false
  pre_tasks:
    - setup:
      tags: [ 'layer1', 'rhosp' ]
  roles:
    - role: layer1_rhosp
      tags: [ 'rhosp', layer1 ]
      mode: create
    - role: layer1_ceph_inventory
      tags: [ 'layer2', 'ceph', 'overcloud', 'overcloud-ceph' ]

- hosts: rhosp-all-group
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'rhosp', 'vm' ], mode: create }

- hosts: rhosp-director-group
  remote_user: root
  gather_facts: false
  roles:
    - role: layer2_rhel_reconfigure_dns
      tags: [ 'layer2', 'rhosp', 'dns' ]
      mode: create
      nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}"
    - role: layer2_rhel
      tags: [ 'layer2', 'rhosp', 'rhel']
      mode: create
    - role: layerX_ipa_client
      tags: [ 'layer2', 'rhosp',  'ipa-client']
      mode: create
      when: "current_lifecycle_env.openstack_version >= 10"
    - role: layer2_ipa_service
      tags: [ 'layer2', 'rhosp',  'ipa-service']
      mode: create
      service: haproxy
      when: "current_lifecycle_env.openstack_version >= 10"
    - role: layer2_rhosp_director
      tags: ['layer2', 'rhosp', 'undercloud' ]
      mode: create

- hosts: overcloud2-director-group
  remote_user: root
  gather_facts: false
  roles:
    - role: layer2_ipa_certificate
      tags: ['layer2', 'rhosp', 'overcloud2', 'overcloud2-cert']
      mode: create
      certcn: 'openstack2.{{ hailstorm_dns_domain }}'
      when: current_lifecycle_env.osp_use_tls
    - role: layer2_rhosp_overcloud_deploy
      tags: ['layer2', 'rhosp', 'overcloud2', 'overcloud2-deploy']
      mode: prepare
      controller: "{{ groups['overcloud2-controller-group'] }}"
      compute: "{{ groups['overcloud2-compute-group'] }}"

- hosts: overcloud-director-group
  remote_user: root
  gather_facts: false
  roles:
    #### Nuage part and just for first director 
    # moved from create-02-nuage.yml
    - role: layer2_rhosp_undercloud_configure_nuage
      tags: ['layer2', 'nuage', 'undercloud-config-nuage']
      mode: create
      when: nuage is defined
    - role: layer2_ipa_certificate
      tags: ['layer2', 'rhosp', 'overcloud', 'overcloud-cert']
      mode: create
      certcn: 'openstack.{{ hailstorm_dns_domain }}'
      when: current_lifecycle_env.osp_use_tls
    # - role: layer2_ceph_openstackconfig
    #   tags: ['layer2', 'rhosp', 'overcloud', 'overcloud-ceph']
    #   mode: create
    #   when: current_lifecycle_env.osp_storage_backend == "ceph_ownvms"
    - role: layer2_rhosp_overcloud_deploy
      tags: ['layer2', 'rhosp', 'overcloud', 'overcloud-deploy']
      mode: create
      controller: "{{ groups['overcloud-controller-group'] }}"
      compute: "{{ groups['overcloud-compute-group'] }}"

- hosts: overcloud-controller-group
  remote_user: root
  gather_facts: false
  roles:
    - role: layer2_rhosp_overcloud_postdeploy_controller
      tags: ['layer2', 'rhosp', 'overcloud', 'overcloud-controller']
      mode: create

- hosts: overcloud-director-group
  remote_user: root
  gather_facts: false
  roles:
    - role: layer2_rhosp_overcloud_configure
      tags: ['layer2', 'rhosp', 'overcloud', 'overcloud-configure']
      mode: create

- hosts: overcloud-controller-group
  remote_user: root
  gather_facts: false
  roles:
    - role: layer2_rhosp_overcloud_configure_lbaas
      tags: ['layer2', 'rhosp', 'overcloud', 'overcloud-controller']
      mode: create
