---
- hosts: satellite-group
  remote_user: root
  gather_facts: false
  roles:
    - role: layer2_satellite_publish_installables
      mode: create
      satellite_www_dir: customer
      installables:
        - CloudbaseInitSetup_x64.msi

- hosts: windows-baseimage-group
  remote_user: root
  gather_facts: false
  roles:
    - role: layer2_vms_managediskimage
      mode: checkvmimage
      tags: [ 'layer2' ]
    - role: layer2_vms
      tags: [ 'layer2', 'vm' ]
      mode: create
      when: not disk_image_exists_in_binary_dir
    - role: layer2_windows_baseimage
      tags: [ 'layer2', 'vm' ]
      mode: create
      satellite_www_dir: customer
      when: not disk_image_exists_in_binary_dir
    - role: layer2_vms_managediskimage
      mode: movevmimage
      tags: [ 'layer2', 'move' ]
      when: not disk_image_exists_in_binary_dir
