- name: restart_openvswitch
  service:
    name: openvswitch
    state: restarted

- name: reload_iptables
  service:
    name: iptables
    state: restarted

- name: sysctl
  shell: sysctl -p

- name: restart_keystone
  service:
    name: httpd
    state: restarted
