- block:
    - include: create_vms.yml
  when: mode == "create" and not windows|default(false,true)

- block:
    - include: create_windows_vm.yml
  when: mode == "create" and windows|default(false,true)

- block:
    - include: start_vms.yml
  when: mode == "start"

- block:
    - include: stop_vms.yml
  when: mode == "stop"

- block:
    - include: destroy_vms.yml
  when: mode == "destroy"

- block:
    - include: snapshot_vm.yml
  when: mode == "snapshot"

- block:
    - include: revert_vm_to_snapshot.yml
  when: mode == "revert"
