- name: patch /etc/default/openvswitch
  lineinfile:
    path: /etc/default/openvswitch
    state: present
    line: "{{ item }}"
    backup: yes
  with_items:
    - "ACTIVE_CONTROLLER={{ hostvars['c1'].vm_nics[1].ip }}"
    - "STANDBY_CONTROLLER={{ hostvars['c2'].vm_nics[1].ip }}"
  notify: restart_openvswitch

- name: copy over selinux rule for nuage
  copy:
    src: ovslocal6.pp
    dest: /root/ovslocal6.pp

- name: add nuage openvswitch selinux rules
  command: semodule -i /root/ovslocal6.pp

- name: allow VLXAN traffic in iptables
  lineinfile:
    path: /etc/sysconfig/iptables
    line: '{{ item }}'
    insertbefore: "log all"
  notify: reload_iptables
  with_items:
    - '-A INPUT -p udp -m multiport --dports 4789 -m comment --comment "Accept VXLAN" -m state --state NEW -j ACCEPT'
    - '-A INPUT -p tcp -m multiport --dports 9697 -m comment --comment "Accept MetaData requests" -m state --state NEW -j ACCEPT'

#https://access.redhat.com/solutions/53031
- name: enable reverse path on controllers to allow requests received from compute nodes via vsr to be sent out directly via br-services
  lineinfile: dest=/etc/sysctl.conf line="{{ item }} = 2" regexp="^{{ item }}"
  with_items:
    - net.ipv4.conf.default.rp_filter
    - net.ipv4.conf.all.rp_filter
  notify: sysctl


- name: Flush handlers
  meta: flush_handlers
