- block:
    - include: configure_ceilometer.yml
    - name: create sensu sudoers file
      template: src=sudoers_sensu.j2 dest=/etc/sudoers.d/sensu
    - include: fix_bugs.yml
    ## enable lbaas UI
    - include: add_nuage_vrs.yml
      when: enable_nuage is defined
    - include: add_lbaas_ui.yml
    - include: create_keystone_domain_files.yml
      tags: configure-keystone
  when: mode=="create"
