---
- hosts: localhost

#
# Configure to match your environment
#
  vars:
    nuage_auth:
      api_username: csproot
      api_password: csproot
      api_enterprise: csp
      api_url: https://10.116.127.156:8443
      api_version: v5_0
    enterprise_name: OpenShift_Org

  tasks:
  - name: Finding Enterprise
    delegate_to: localhost
    nuage_vspk:
      auth: "{{ nuage_auth }}"
      type: Enterprise
      command: find
      properties:
        name: "{{ enterprise_name }}"
    register: nuage_enterprise

  - name: Fetching all Domains
    delegate_to: localhost
    nuage_vspk:
      auth: "{{ nuage_auth }}"
      type: Domain
      parent_id: "{{ nuage_enterprise.id }}"
      parent_type: Enterprise
      command: find
    ignore_errors: yes
    register: nuage_domains

#  - debug:
#      var: nuage_domains

  - name: Fetching all container interfaces
    delegate_to: localhost
    nuage_vspk:
      auth: "{{ nuage_auth }}"
      type: ContainerInterface 
      command: find
      parent_id: "{{ item.ID }}"
      parent_type: Domain
    with_items: "{{ nuage_domains.entities }}"
    ignore_errors: yes
    when: nuage_domains.entities is defined
    register: nuage_containerinterfaces

  - include_tasks: delete_containerinterfaces.yml nuage_containerinterfaces_results="{{result_item}}"
    with_items: "{{ nuage_containerinterfaces.results }}"
    loop_control:
      loop_var: result_item
    when: nuage_containerinterfaces.results is defined

  - name: Fetching all vports
    delegate_to: localhost
    nuage_vspk:
      auth: "{{ nuage_auth }}"
      type: VPort
      command: find
      parent_id: "{{ item.ID }}"
      parent_type: Domain
    with_items: "{{ nuage_domains.entities }}"
    ignore_errors: yes
    when: nuage_domains.entities is defined
    register: nuage_vports

#  - debug:
#      var: nuage_vports.results[0]

  - include_tasks: delete_vports.yml nuage_vports_results="{{result_item}}"
    with_items: "{{ nuage_vports.results }}"
    loop_control:
      loop_var: result_item
    when: nuage_vports.results is defined

  - name: Deleting all found Domains
    delegate_to: localhost
    nuage_vspk:
      auth: "{{ nuage_auth }}"
      type: Domain
      state: absent
      id: "{{ item.ID }}"
    with_items: "{{ nuage_domains.entities }}"
    when: nuage_domains.entities is defined

  - name: Fetching all Domain Templates
    delegate_to: localhost
    nuage_vspk:
      auth: "{{ nuage_auth }}"
      type: DomainTemplate
      parent_id: "{{ nuage_enterprise.id }}"
      parent_type: Enterprise
      command: find
    ignore_errors: yes
    register: nuage_domaintemplates

  - name: Deleting all found Domain Templates
    delegate_to: localhost
    nuage_vspk:
      auth: "{{ nuage_auth }}"
      type: DomainTemplate
      state: absent
      id: "{{ item.ID }}"
    with_items: "{{ nuage_domaintemplates.entities }}"
    when: nuage_domaintemplates.entities is defined
