- name: copy chrony configuration for RHEL7
  template: src=chrony.j2
     dest=/etc/chrony.conf
     owner=root
     group=root
     mode=0644
  register: chrony_conf

- name: ensure chrony service is started and enabled
  service:
   name: chronyd
   state: started
   enabled: yes

- name: ensure chrony is getting restarted if necessary
  service:
   name: chronyd
   state: restarted
  when: chrony_conf|changed
#  - name: Join CloudForms/ManageIQ region
#      command: appliance_console_cli --fetch-key  cloudforms-db01.{{ hailstorm_dns_domain }} --sshlogin root --sshpassword {{ root_password }} --hostname cloudforms-db01.{{ hailstorm_dns_domain }} --password {{ root_password }}
#appliance_console_cli --host=cloudforms.example.com --region=919 --internal --password="redhat01" --key --force-key --dbdisk=/dev/vdb --sshpassword="redhat01"


- name: Join WebUI to the Master Region 919
  shell: >
    LC_CTYPE= appliance_console_cli
    --fetch-key=cloudforms-db01.{{ hailstorm_dns_domain }}
    --sshlogin=root
    --sshpassword="{{ root_password }}"
    --hostname=cloudforms-db01.{{ hailstorm_dns_domain }}
    --password="{{ root_password }}"
    creates=/var/www/miq/vmdb/log/appliance_console.log

- name: wait for cfme web ui to become available
#  wait_for: host={{ hostvars[cfmehostname.stdout].vm_nics[0].ip }} port=443 timeout=600
  wait_for: host="{{ ansible_host }}" port=443 timeout=600
  delegate_to: "{{ infrastructure_delegate_host_used_to_test_if_layer2_host_is_available }}"

- name: Create Zone WebUI
  shell: "/var/www/miq/vmdb/bin/rails runner 'Zone.create(:name => \"WebUI\", :description => \"WebUI Zone\")'"

- name: Move WebUI server to WebUI Zone
  command: "/var/www/miq/vmdb/bin/rails runner 'MiqServer.my_server.set_config(:server => {:zone => \"WebUI\"})'"


- name: perform appliance IPA integration
  shell: >
    LC_CTYPE= appliance_console_cli
    --ipaserver {{ hostvars['ipa'].hostname }}
    --ipadomain {{ hailstorm_dns_domain}}
    --iparealm {{ hailstorm_dns_domain|upper }}
    --ipaprincipal admin
    --ipapassword "{{ root_password }}"
    creates=/etc/sssd/sssd.conf

- name: set internal admin password
  shell: cd /var/www/miq/vmdb && rails r "User.find_by_userid('admin').update_attributes(:password => '{{ root_password }}')"
  #https://access.redhat.com/solutions/801103
