- name: Copy certificate to the proxy server
  copy:
    dest: /etc/pki/tls/certs/squid.pem
    content: "{{ lookup('file','binary/alienca.cert.pem') }}\n{{ lookup('file','binary/alienca.key.pem') }}"
    owner: squid
    group: squid
    mode: 0640


- name: Configure squid port 3128 to use ssl
  lineinfile:
    path: /etc/squid/squid.conf
    regexp: '^http_port 3128'
    line: 'http_port 3128 ssl-bump cert=/etc/pki/tls/certs/squid.pem  generate-host-certificates=on dynamic_cert_mem_cache_size=4MB'
  register: configure_ssl

- name: Configure squid ssl_bump
  blockinfile:
    path: /etc/squid/squid.conf
    insertafter: "^http_port"
    marker: "# {mark} ANSIBLE MANAGED BLOCK ssl_bump"
    content: |
       sslcrtd_program /usr/lib64/squid/ssl_crtd  -s /var/lib/ssl_db -M 4MB
       acl step1 at_step SslBump1
       ssl_bump peek step1
       ssl_bump bump all
  register: configure_ssl_bump

- name: Install passlib to use htpasswd modfule
  yum:
    name: python-passlib
    state: present
    enablerepo: rhel-7-server-extras-rpms

- htpasswd:
    path: /etc/squid/htpasswd
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    owner: squid
    group: squid
    mode: 0640
  with_items:
    - "{{ proxy_users }}"

- name: Configure squid for LDAP authentication
  blockinfile:
    path: /etc/squid/squid.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK auth"
    insertafter: "^acl CONNECT method CONNECT"
    content: |
      auth_param basic program /usr/lib64/squid/basic_ncsa_auth /etc/squid/htpasswd
      auth_param basic children 5
      auth_param basic realm Web-Proxy
      auth_param basic credentialsttl 1 minute
      acl auth proxy_auth REQUIRED
  register: configure_ldap

- name: Disable full access from the localnet
  lineinfile:
    path: /etc/squid/squid.conf
    regexp: "#?http_access allow localnet"
    line: "#http_access allow localnet"
- name: Allow only users authenticated
  blockinfile:
    path: /etc/squid/squid.conf
    insertbefore: "^http_access deny all"
    content: |
       http_access allow auth





- name: Create ssl db directory for squid
  command: /usr/lib64/squid/ssl_crtd  -c -s /var/lib/ssl_db
  args:
    creates: /var/lib/ssl_db/index.txt

- name: Change permission to directory /var/lib/ssl_db
  command: chown -R squid:squid /var/lib/ssl_db
  changed_when: False

- name: Set SElinux content for /var/lib/ssl_db
  command: chcon -R -u system_u -r object_r -t squid_cache_t /var/lib/ssl_db
  changed_when: False

- name: Open firewalld port
  firewalld:
    service: squid
    permanent: true
    immediate: true
    state: enabled

- name: Enable squid service
  service:
    name: squid
    enabled: True
    state: started

- name: Restart squid if was configured
  service:
    name: squid
    state: restarted
  when: configure_ssl|changed or configure_ssl_bump|changed or configure_ldap|changed
